// ==UserScript==
// @name         Reposition Octotree bookmark icon
// @version      1.0.2
// @description  https://github.com/ovity/octotree/issues/992
// @author       kidonng
// @namespace    https://github.com/kidonng/cherry
// @match        https://github.com/*
// ==/UserScript==
(()=>{var N=Symbol("null"),M=0,E=class extends Map{constructor(){super();this._objectHashes=new WeakMap,this._symbolHashes=new Map,this._publicKeys=new Map;let[e]=arguments;if(e!=null){if(typeof e[Symbol.iterator]!="function")throw new TypeError(typeof e+" is not iterable (cannot read property Symbol(Symbol.iterator))");for(let[r,n]of e)this.set(r,n)}}_getPublicKeys(e,r=!1){if(!Array.isArray(e))throw new TypeError("The keys parameter must be an array");let n=this._getPrivateKey(e,r),o;return n&&this._publicKeys.has(n)?o=this._publicKeys.get(n):r&&(o=[...e],this._publicKeys.set(n,o)),{privateKey:n,publicKey:o}}_getPrivateKey(e,r=!1){let n=[];for(let o of e){o===null&&(o=N);let s=typeof o=="object"||typeof o=="function"?"_objectHashes":typeof o=="symbol"?"_symbolHashes":!1;if(!s)n.push(o);else if(this[s].has(o))n.push(this[s].get(o));else if(r){let c=`@@mkm-ref-${M++}@@`;this[s].set(o,c),n.push(c)}else return!1}return JSON.stringify(n)}set(e,r){let{publicKey:n}=this._getPublicKeys(e,!0);return super.set(n,r)}get(e){let{publicKey:r}=this._getPublicKeys(e);return super.get(r)}has(e){let{publicKey:r}=this._getPublicKeys(e);return super.has(r)}delete(e){let{publicKey:r,privateKey:n}=this._getPublicKeys(e);return Boolean(r&&super.delete(r)&&this._publicKeys.delete(n))}clear(){super.clear(),this._symbolHashes.clear(),this._publicKeys.clear()}get[Symbol.toStringTag](){return"ManyKeysMap"}get size(){return super.size}},P=E;function k(){let t={};return t.promise=new Promise((e,r)=>{t.resolve=e,t.reject=r}),t}var g=k;var F=Object.defineProperty,x=(t,e,r)=>(typeof e!="symbol"&&(e+=""),e in t?F(t,e,{enumerable:!0,configurable:!0,writable:!0,value:r}):t[e]=r),O=(t,e,r)=>{if(!e.has(t))throw TypeError("Cannot "+r)},l=(t,e,r)=>(O(t,e,"read from private field"),r?r.call(t):e.get(t)),i=(t,e,r,n)=>(O(t,e,"write to private field"),n?n.call(t,r):e.set(t,r),r),a,p,u,I=class{constructor(e){x(this,"value"),x(this,"next"),this.value=e}},C=class{constructor(){a.set(this,void 0),p.set(this,void 0),u.set(this,void 0),this.clear()}enqueue(e){var r;let n=new I(e);l(this,a)?(l(this,p).next=n,i(this,p,n)):(i(this,a,n),i(this,p,n)),i(this,u,(r=+l(this,u))+1)}dequeue(){var e;let r=l(this,a);if(!!r)return i(this,a,l(this,a).next),i(this,u,(e=+l(this,u))-1),r.value}clear(){i(this,a,void 0),i(this,p,void 0),i(this,u,0)}get size(){return l(this,u)}*[Symbol.iterator](){let e=l(this,a);for(;e;)yield e.value,e=e.next}};a=new WeakMap;p=new WeakMap;u=new WeakMap;var j=(t,e,r,n)=>{if(r==="length"||r==="prototype"||r==="arguments"||r==="caller")return;let o=Object.getOwnPropertyDescriptor(t,r),s=Object.getOwnPropertyDescriptor(e,r);!q(o,s)&&n||Object.defineProperty(t,r,s)},q=function(t,e){return t===void 0||t.configurable||t.writable===e.writable&&t.enumerable===e.enumerable&&t.configurable===e.configurable&&(t.writable||t.value===e.value)},R=(t,e)=>{let r=Object.getPrototypeOf(e);r!==Object.getPrototypeOf(t)&&Object.setPrototypeOf(t,r)},A=(t,e)=>`/* Wrapped ${t}*/
${e}`,V=Object.getOwnPropertyDescriptor(Function.prototype,"toString"),z=Object.getOwnPropertyDescriptor(Function.prototype.toString,"name"),D=(t,e,r)=>{let n=r===""?"":`with ${r.trim()}() `,o=A.bind(null,n,e.toString());Object.defineProperty(o,"name",z),Object.defineProperty(t,"toString",{...V,value:o})};function W(t,e,{ignoreNonConfigurable:r=!1}={}){let{name:n}=t;for(let o of Reflect.ownKeys(e))j(t,e,o,r);return R(t,e),D(t,e,n),t}var T=W;var m=new WeakMap,$=(t,e={})=>{if(typeof t!="function")throw new TypeError("Expected a function");let r,n=0,o=t.displayName||t.name||"<anonymous>",s=function(...c){if(m.set(s,++n),n===1)r=t.apply(this,c),t=null;else if(e.throw===!0)throw new Error(`Function \`${o}\` can only be called once`);return r};return T(s,t),m.set(s,n),s};$.callCount=t=>{if(!m.has(t))throw new Error(`The given function \`${t.name}\` is not wrapped by the \`onetime\` package`);return m.get(t)};var v=new P,H=t=>["interactive","complete"].includes((t.ownerDocument||t).readyState);function Y(t,{target:e=document,stopOnDomReady:r=!0,waitForChildren:n=!0,timeout:o=Number.POSITIVE_INFINITY,predicate:s}={}){let c=[t,r,o,n,e],S=v.get(c);if(S)return S;let _,K=g(),{promise:b}=K;v.set(c,b);let f=w=>{cancelAnimationFrame(_),v.delete(c,b),K.resolve(w)};return o!==Number.POSITIVE_INFINITY&&setTimeout(f,o),function w(){let y=L({target:e,selector:t,predicate:s});if(H(e)&&(r||y)){f(y||void 0);return}let h=y;for(;h;){if(!n||h.nextSibling){f(y);return}h=h.parentElement}_=requestAnimationFrame(w)}(),Object.assign(b,{stop:()=>f()})}function L({target:t,selector:e,predicate:r}={}){return r?[...t.querySelectorAll(e)].find(o=>r(o)):t.querySelector(e)}var d=Y;(async()=>{let t=await d(".gh-header-title .octotree-btn",{stopOnDomReady:!1});t.parentElement.prepend(t),t.style.position="relative",t.style.left="-25px",t.style.marginRight="-25px"})();})();
