name: Build Scripts

on:
    workflow_dispatch: null
    push:
        paths:
            - scripts

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: |
                  yarn
                  yarn build-script
                  yarn build-bookmarklet
            - name: Upload
              run: |
                  tmp=$(mktemp -d)
                  mv scripts/generated/*.js $tmp
                  cd $tmp
                  git init -b gh-pages .
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m Build
                  git push $GITHUB_SERVER_URL/$GITHUB_REPOSITORY gh-pages -f
